code --install-extension johnpapa.Angular2
code --install-extension Angular.ng-template
code --install-extension EditorConfig.EditorConfig
code --install-extension natewallace.angular2-inline
code --install-extension vismalietuva.vscode-angular-support
code --install-extension mgmcdermott.vscode-language-babel
code --install-extension robinbentley.sass-indented
code --install-extension mhmadhamster.postcss-language
code --install-extension eg2.vscode-npm-script
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension eg2.tslint
code --install-extension dbaeumer.vscode-eslint
code --install-extension esbenp.prettier-vscode
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension steoates.autoimport
code --install-extension formulahendry.auto-rename-tag
code --install-extension formulahendry.auto-close-tag
code --install-extension donjayamanne.githistory
code --install-extension abusaidm.html-snippets
code --install-extension alefragnani.Bookmarks
code --install-extension naumovs.color-highlight
code --install-extension yzhang.markdown-all-in-one
code --install-extension wayou.vscode-todo-highlight
code --install-extension DotJoshJohnson.xml
code --install-extension redhat.vscode-yaml
code --install-extension mikestead.dotenv
code --install-extension konstantin.wrapSelection
code --install-extension WallabyJs.quokka-vscode
code --install-extension flowtype.flow-for-vscode
code --install-extension Tyriar.shell-launcher
code --install-extension robertohuertasm.vscode-icons
code --install-extension okon3.ayu-miragemod
code --install-extension peterjausovec.vscode-docker