code --install-extension Mikael.Angular-BeastCode
code --install-extension johnpapa.Angular2
code --install-extension vismalietuva.vscode-angular-support
code --install-extension formulahendry.auto-close-tag
code --install-extension steoates.autoimport
code --install-extension formulahendry.auto-rename-tag
code --install-extension okon3.ayu-miragemod
code --install-extension mgmcdermott.vscode-language-babel
code --install-extension alefragnani.Bookmarks
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension ms-vscode.cpptools
code --install-extension jbenden.c-cpp-flylint
code --install-extension mitaki28.vscode-clang
code --install-extension ms-vscode.csharp
code --install-extension powered by OmniSharp
code --install-extension jchannon.csharpextensions
code --install-extension Leopotam.csharpfixformat
code --install-extension austin.code-gnu-global
code --install-extension formulahendry.code-runner
code --install-extension naumovs.color-highlight
code --install-extension oleg-shilo.cs-script
code --install-extension no .NET Core required
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension PeterJausovec.vscode-docker
code --install-extension joelday.docthis
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.githistory
code --install-extension abusaidm.html-snippets
code --install-extension jsynowiec.vscode-insertdatestring
code --install-extension xabikos.JavaScriptSnippets
code --install-extension James-Yu.latex-workshop
code --install-extension negokaz.live-server-preview
code --install-extension yzhang.markdown-all-in-one
code --install-extension ms-vscode.mono-debug
code --install-extension christian-kohler.npm-intellisense
code --install-extension eg2.vscode-npm-script
code --install-extension jmrog.vscode-nuget-package-manager
code --install-extension sivarajanraju.vs-code-office-ui-fabric
code --install-extension techer.open-in-browser
code --install-extension christian-kohler.path-intellisense
code --install-extension esbenp.prettier-vscode
code --install-extension WallabyJs.quokka-vscode
code --install-extension humao.rest-client
code --install-extension robinbentley.sass-indented
code --install-extension Tyriar.shell-launcher
code --install-extension wayou.vscode-todo-highlight
code --install-extension eg2.tslint
code --install-extension rbbit.typescript-hero
code --install-extension emmanuelbeziat.vscode-great-icons
code --install-extension konstantin.wrapSelection
code --install-extension DotJoshJohnson.xml
code --install-extension adamvoss.yaml